CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    passworde VARCHAR(255) NOT NULL,
    rol INT NOT NULL
);

INSERT INTO messages (username, passworde, rol)
VALUES ('admin', '$argon2id$v=19$m=16384,t=2,p=1$...hash...', 1);